java_test(
    name = "FormattingFilerTest",
    srcs = ["FormattingFilerTest.java"],
    deps = [
        "//core/src/main/java/com/google/googlejavaformat/java/filer",
        "//thirdparty/jvm/com/google/guava",
        "//thirdparty/jvm/com/google/testing/compile:compile_testing",
        "//thirdparty/jvm/com/google/truth",
        "//thirdparty/jvm/junit",
    ],
)
