package(default_visibility = ["//:__subpackages__"])

java_library(
    name = "filer",
    srcs = glob(["*.java"]),
    deps = [
        "//core/src/main/java/com/google/googlejavaformat/java",
        "//thirdparty/jvm/com/google/code/findbugs:jsr305",
        "//thirdparty/jvm/com/google/guava",
    ],
)
