java_test(
    name = "NewlinesTest",
    srcs = ["NewlinesTest.java"],
    deps = [
        "//core/src/main/java/com/google/googlejavaformat",
        "//thirdparty/jvm/com/google/guava",
        "//thirdparty/jvm/com/google/truth",
        "//thirdparty/jvm/junit",
    ],
)
